# NER and Entity Resolution - Baseline spaCy
This work is a part of the knowledge graph pipeline built for 26 Spring BigCo Studio at Cornell Tech, and belongs to Team 10.

The whole process of this part is run on Google Colab.

# 1. Set up GDrive

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
%cd /content/gdrive/MyDrive/NER_EntityResolution

/content/gdrive/MyDrive/NER_EntityResolution

# 2. Install required packages

In [ ]:
!pip install -q pandas spacy
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 98.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

# 3. Preprocess data

In [ ]:
!python src/preprocess.py \
  --input data/mock/mock2_input.csv \
  --cleaned-output data/processed/cleaned_input_mock2.csv \
  --invalid-output data/processed/invalid_rows_mock2.csv

[preprocess] Wrote 53 valid row(s) to: data/processed/cleaned_input_mock2.csv
[preprocess] Wrote 7 invalid row(s) to: data/processed/invalid_rows_mock2.csv

In [ ]:
!ls data/processed/

cleaned_input_mock1.csv  invalid_rows_mock1.csv
cleaned_input_mock2.csv  invalid_rows_mock2.csv

In [ ]:
import pandas as pd

cleaned_df = pd.read_csv("data/processed/cleaned_input_mock2.csv")
invalid_df = pd.read_csv("data/processed/invalid_rows_mock2.csv")

print("Cleaned input:")
display(cleaned_df)

print("Invalid rows:")
display(invalid_df)

Cleaned input:

,source_id,source_type,raw_text,source_url,date,company_seed,source_type_cleaned,raw_text_cleaned,source_url_cleaned,date_cleaned,company_seed_cleaned,company_seed_invalid,company_seed_invalid_reason,row_invalid_reasons,row_valid_for_ner
0,1,SEC,Pfizer acquired Seagen in 2023.,https://example.com/sec1,2023-01,Pfizer,SEC,Pfizer acquired Seagen in 2023.,https://example.com/sec1,2023-01,Pfizer,False,NaN,NaN,True
1,2,SEC,Merck entered into a license agreement with Mo...,https://example.com/sec2,2024-02,Merck,SEC,Merck entered into a license agreement with Mo...,https://example.com/sec2,2024-02,Merck,False,NaN,NaN,True
2,3,USPTO,Regeneron and Sanofi jointly developed an anti...,https://example.com/uspto1,2022-06,Regeneron,USPTO,Regeneron and Sanofi jointly developed an anti...,https://example.com/uspto1,2022-06,Regeneron,False,NaN,NaN,True
3,4,PUBMED,CSL Behring collaborated with Takeda on plasma...,https://example.com/pubmed1,2021-11,CSL Behring,PUBMED,CSL Behring collaborated with Takeda on plasma...,https://example.com/pubmed1,2021-11,CSL Behring,False,NaN,NaN,True
4,5,SEC,Bristol Myers Squibb purchased Karuna Therapeu...,https://example.com/sec3,2024-12,Bristol Myers Squibb,SEC,Bristol Myers Squibb purchased Karuna Therapeu...,https://example.com/sec3,2024-12,Bristol Myers Squibb,False,NaN,NaN,True
5,6,USPTO,AbbVie filed patent with Genmab for a bispecif...,https://example.com/uspto2,2020-09,AbbVie,USPTO,AbbVie filed patent with Genmab for a bispecif...,https://example.com/uspto2,2020-09,AbbVie,False,NaN,NaN,True
6,7,SEC,AstraZeneca partnered with Daiichi Sankyo to c...,https://example.com/sec4,2023-08,AstraZeneca,SEC,AstraZeneca partnered with Daiichi Sankyo to c...,https://example.com/sec4,2023-08,AstraZeneca,False,NaN,NaN,True
7,8,PUBMED,Novartis worked with Alnylam on RNA interferen...,https://example.com/pubmed2,2022-03,Novartis,PUBMED,Novartis worked with Alnylam on RNA interferen...,https://example.com/pubmed2,2022-03,Novartis,False,NaN,NaN,True
8,9,SEC,10X GENOMICS INC acquired a small diagnostics ...,https://example.com/sec5,2024-03,10X Genomics,SEC,10X GENOMICS INC acquired a small diagnostics ...,https://example.com/sec5,2024-03,10X Genomics,False,NaN,NaN,True
9,10,SEC,10X GENOMICS BV entered into a collaboration w...,https://example.com/sec6,2024-04,10X Genomics,SEC,10X GENOMICS BV entered into a collaboration w...,https://example.com/sec6,2024-04,10X Genomics,False,NaN,NaN,True
10,11,SEC,10X GENOMICS SWEDEN AB licensed imaging techno...,https://example.com/sec7,2024-05,10X Genomics,SEC,10X GENOMICS SWEDEN AB licensed imaging techno...,https://example.com/sec7,2024-05,10X Genomics,False,NaN,NaN,True
11,12,PUBMED,CSL Behring GmbH developed a plasma therapy al...,https://example.com/pubmed3,2022-09,CSL Behring,PUBMED,CSL Behring GmbH developed a plasma therapy al...,https://example.com/pubmed3,2022-09,CSL Behring,False,NaN,NaN,True
12,13,SEC,"Pfizer Inc. acquired Seagen, according to the ...",https://example.com/sec8,2023-02,Pfizer,SEC,"Pfizer Inc. acquired Seagen, according to the ...",https://example.com/sec8,2023-02,Pfizer,False,NaN,NaN,True
13,14,SEC,PFIZER acquired SEAGEN in a merger transaction.,https://example.com/sec9,2023-03,Pfizer,SEC,PFIZER acquired SEAGEN in a merger transaction.,https://example.com/sec9,2023-03,Pfizer,False,NaN,NaN,True
14,15,USPTO,"Regeneron Pharmaceuticals, Inc. and Sanofi co-...",https://example.com/uspto3,2021-07,Regeneron,USPTO,"Regeneron Pharmaceuticals, Inc. and Sanofi co-...",https://example.com/uspto3,2021-07,Regeneron,False,NaN,NaN,True
15,16,PUBMED,BMS collaborated with 2seventy bio on cell the...,https://example.com/pubmed4,2023-06,Bristol Myers Squibb,PUBMED,BMS collaborated with 2seventy bio on cell the...,https://example.com/pubmed4,2023-06,Bristol Myers Squibb,False,NaN,NaN,True
16,17,SEC,"Moderna, Inc. entered into a license agree...",https://example.com/sec10,2023-10,Moderna,SEC,"Moderna, Inc. entered into a license agreement...",https://example.com/sec10,2023-10,Moderna,False,NaN,NaN,True
17,18,SEC,"Gilead Sciences, Inc. acquired CymaBay Thera...",https://example.com/sec11,2024-01,Gilead Sciences,SEC,"Gilead Sciences, Inc. acquired CymaBay Therape...",https://example.com/sec11,2024-01,Gilead Sciences,False,NaN,NaN,True
18,19,USPTO,argenx SE co-filed a patent with Johnson & Joh...,https://example.com/uspto4,2021-05,argenx,USPTO,argenx SE co-filed a patent with Johnson & Joh...,https://example.com/uspto4,2021-05,argenx,False,NaN,NaN,True
19,20,PUBMED,bluebird bio partnered with Bristol-Myers Squi...,https://example.com/pubmed5,2020-08,bluebird bio,PUBMED,bluebird bio partnered with Bristol-Myers Squi...,https://example.com/pubmed5,2020-08,bluebird bio,False,NaN,NaN,True
20,21,SEC,Sarepta Therapeutics merged with Example Rare ...,https://example.com/sec12,2022-04,Sarepta Therapeutics,SEC,Sarepta Therapeutics merged with Example Rare ...,https://example.com/sec12,2022-04,Sarepta Therapeutics,False,NaN,NaN,True
21,22,PUBMED,CRISPR Therapeutics collaborated with Vertex P...,https://example.com/pubmed6,2022-10,CRISPR Therapeutics,PUBMED,CRISPR Therapeutics collaborated with Vertex P...,https://example.com/pubmed6,2022-10,CRISPR Therapeutics,False,NaN,NaN,True
22,29,SEC,12345 acquired 67890.,https://example.com/bad7,2024-01,12345,SEC,12345 acquired 67890.,https://example.com/bad7,2024-01,12345,False,NaN,NaN,True
23,30,PUBMED,-- collaborated with @@##.,https://example.com/bad8,2020-03,--,PUBMED,-- collaborated with @@##.,https://example.com/bad8,2020-03,--,False,NaN,NaN,True
24,31,SEC,TBD entered into a licensing agreement.,https://example.com/bad9,2024-06,TBD,SEC,TBD entered into a licensing agreement.,https://example.com/bad9,2024-06,TBD,False,NaN,NaN,True
25,32,USPTO,Example text with no company at all.,https://example.com/bad10,2021-12,NoCompany,USPTO,Example text with no company at all.,https://example.com/bad10,2021-12,NoCompany,False,NaN,NaN,True
26,33,SEC,Pfizer acquired Seagen in 2023. The deal expan...,https://example.com/sec13,2023-01,Pfizer,SEC,Pfizer acquired Seagen in 2023. The deal expan...,https://example.com/sec13,2023-01,Pfizer,False,NaN,NaN,True
27,34,SEC,"Merck licensed technology from Moderna. Later,...",https://example.com/sec14,2024-02,Merck,SEC,"Merck licensed technology from Moderna. Later,...",https://example.com/sec14,2024-02,Merck,False,NaN,NaN,True
28,35,USPTO,AbbVie filed patent with Genmab. In a separate...,https://example.com/uspto5,2022-11,AbbVie,USPTO,AbbVie filed patent with Genmab. In a separate...,https://example.com/uspto5,2022-11,AbbVie,False,NaN,NaN,True
29,36,PUBMED,Novartis collaborated with Alnylam on siRNA de...,https://example.com/pubmed7,2023-07,Novartis,PUBMED,Novartis collaborated with Alnylam on siRNA de...,https://example.com/pubmed7,2023-07,Novartis,False,NaN,NaN,True
30,37,SEC,CSL Behring and CSL Behring GmbH were both ref...,https://example.com/sec15,2023-09,CSL Behring,SEC,CSL Behring and CSL Behring GmbH were both ref...,https://example.com/sec15,2023-09,CSL Behring,False,NaN,NaN,True
31,38,SEC,10X Genomics Sweden AB and 10X Genomics BV wer...,https://example.com/sec16,2024-07,10X Genomics,SEC,10X Genomics Sweden AB and 10X Genomics BV wer...,https://example.com/sec16,2024-07,10X Genomics,False,NaN,NaN,True
32,39,PUBMED,J&J worked with Johnson and Johnson Innovative...,https://example.com/pubmed8,2022-01,Johnson & Johnson,PUBMED,J&J worked with Johnson and Johnson Innovative...,https://example.com/pubmed8,2022-01,Johnson & Johnson,False,NaN,NaN,True
33,40,USPTO,"Regeneron and Regeneron Pharmaceuticals, Inc. ...",https://example.com/uspto6,2021-03,Regeneron,USPTO,"Regeneron and Regeneron Pharmaceuticals, Inc. ...",https://example.com/uspto6,2021-03,Regeneron,False,NaN,NaN,True
34,41,SEC,Eli Lilly acquired POINT Biopharma to strength...,https://example.com/sec17,2023-10,Eli Lilly,SEC,Eli Lilly acquired POINT Biopharma to strength...,https://example.com/sec17,2023-10,Eli Lilly,False,NaN,NaN,True
35,42,SEC,Roche entered into a collaboration with Recurs...,https://example.com/sec18,2024-01,Roche,SEC,Roche entered into a collaboration with Recurs...,https://example.com/sec18,2024-01,Roche,False,NaN,NaN,True
36,43,PUBMED,Takeda worked with Arrowhead Pharmaceuticals o...,https://example.com/pubmed9,2021-04,Takeda,PUBMED,Takeda worked with Arrowhead Pharmaceuticals o...,https://example.com/pubmed9,2021-04,Takeda,False,NaN,NaN,True
37,44,USPTO,Amgen co-filed a patent with Generate Biomedic...,https://example.com/uspto7,2024-02,Amgen,USPTO,Amgen co-filed a patent with Generate Biomedic...,https://example.com/uspto7,2024-02,Amgen,False,NaN,NaN,True
38,45,SEC,Biogen licensed a neurodegeneration program fr...,https://example.com/sec19,2023-11,Biogen,SEC,Biogen licensed a neurodegeneration program fr...,https://example.com/sec19,2023-11,Biogen,False,NaN,NaN,True
39,46,PUBMED,GSK partnered with CureVac on next-generation ...,https://example.com/pubmed10,2022-05,GSK,PUBMED,GSK partnered with CureVac on next-generation ...,https://example.com/pubmed10,2022-05,GSK,False,NaN,NaN,True
40,47,SEC,Johnson & Johnson acquired Shockwave Medical.,https://example.com/sec20,2024-06,Johnson & Johnson,SEC,Johnson & Johnson acquired Shockwave Medical.,https://example.com/sec20,2024-06,Johnson & Johnson,False,NaN,NaN,True
41,48,USPTO,Novo Nordisk filed patent with Valo Health on ...,https://example.com/uspto8,2023-12,Novo Nordisk,USPTO,Novo Nordisk filed patent with Valo Health on ...,https://example.com/uspto8,2023-12,Novo Nordisk,False,NaN,NaN,True
42,49,SEC,Acme Bio collaborated with Beta Pharma.,NaN,2023-13,Acme Bio,SEC,Acme Bio collaborated with Beta Pharma.,NaN,2023-13,Acme Bio,False,NaN,NaN,True
43,51,SEC,BioNTech entered into a collaboration with Gen...,https://example.com/sec21,2023-09,Pfizer,SEC,BioNTech entered into a collaboration with Gen...,https://example.com/sec21,2023-09,Pfizer,False,NaN,NaN,True
44,52,PUBMED,Sanofi worked with Regeneron on immunology pro...,https://example.com/pubmed11,2020-10,Takeda,PUBMED,Sanofi worked with Regeneron on immunology pro...,https://example.com/pubmed11,2020-10,Takeda,False,NaN,NaN,True
45,53,SEC,"""Moderna"" acquired 'Example Vaccine Co'.",https://example.com/sec22,2023-02,Moderna,SEC,"""Moderna"" acquired 'Example Vaccine Co'.",https://example.com/sec22,2023-02,Moderna,False,NaN,NaN,True
46,54,PUBMED,Seagen/Genmab collaboration was discussed in t...,https://example.com/pubmed12,2021-02,Seagen,PUBMED,Seagen/Genmab collaboration was discussed in t...,https://example.com/pubmed12,2021-02,Seagen,False,NaN,NaN,True
47,55,USPTO,"Merck & Co., Inc.; Moderna, Inc. ; and BioNTec...",https://example.com/uspto9,2024-03,Merck,USPTO,"Merck & Co., Inc.; Moderna, Inc. ; and BioNTec...",https://example.com/uspto9,2024-03,Merck,False,NaN,NaN,True
48,56,SEC,Pfizer licensed technology from Beam ...,https://example.com/sec23,2024-04,Pfizer,SEC,Pfizer licensed technology from Beam Therapeutics,https://example.com/sec23,2024-04,Pfizer,False,NaN,NaN,True
49,57,PUBMED,FDA collaborated with Pfizer on regulatory sci...,https://example.com/pubmed13,2022-06,Pfizer,PUBMED,FDA collaborated with Pfizer on regulatory sci...,https://example.com/pubmed13,2022-06,Pfizer,False,NaN,NaN,True
50,58,SEC,University of Pennsylvania licensed technology...,https://example.com/sec24,2020-09,Spark Therapeutics,SEC,University of Pennsylvania licensed technology...,https://example.com/sec24,2020-09,Spark Therapeutics,False,NaN,NaN,True
51,59,SEC,Alnylam acquired Example RNA Startup.,not_a_url,2024-05,Alnylam,SEC,Alnylam acquired Example RNA Startup.,not_a_url,2024-05,Alnylam,False,NaN,NaN,True
52,60,PUBMED,Example Biotech worked with Example Diagnostics.,https://example.com/pubmed14,NaN,Example Biotech,PUBMED,Example Biotech worked with Example Diagnostics.,https://example.com/pubmed14,NaN,Example Biotech,False,NaN,NaN,True

Invalid rows:

,source_id,source_type,raw_text,source_url,date,company_seed,source_type_cleaned,raw_text_cleaned,source_url_cleaned,date_cleaned,company_seed_cleaned,company_seed_invalid,company_seed_invalid_reason,row_invalid_reasons,row_valid_for_ner
0,23,SEC,#NAME? filed a report.,https://example.com/bad1,2021-07,#NAME?,SEC,#NAME? filed a report.,https://example.com/bad1,2021-07,#NAME?,True,excel_error_token,excel_error_token,False
1,24,USPTO,11-JUL appears in the assignee field.,https://example.com/bad2,2020-05,11-JUL,USPTO,11-JUL appears in the assignee field.,https://example.com/bad2,2020-05,11-JUL,True,date_like_token,date_like_token,False
2,25,SEC,NaN,https://example.com/bad3,2022-02,Unknown,SEC,NaN,https://example.com/bad3,2022-02,Unknown,False,NaN,missing_raw_text,False
3,26,PUBMED,,https://example.com/bad4,2023-01,BlankCo,PUBMED,NaN,https://example.com/bad4,2023-01,BlankCo,False,NaN,missing_raw_text,False
4,27,SEC,N/A entered into a collaboration.,https://example.com/bad5,2022-06,NaN,SEC,N/A entered into a collaboration.,https://example.com/bad5,2022-06,NaN,True,missing_company_seed,missing_company_seed,False
5,28,USPTO,NULL filed patent with ???.,https://example.com/bad6,2021-09,NaN,USPTO,NULL filed patent with ???.,https://example.com/bad6,2021-09,NaN,True,missing_company_seed,missing_company_seed,False
6,50,UNKNOWN,Omega Therapeutics acquired ExampleCo.,https://example.com/unknown1,2022-07,Omega Therapeutics,UNKNOWN,Omega Therapeutics acquired ExampleCo.,https://example.com/unknown1,2022-07,Omega Therapeutics,False,NaN,unknown_source_type,False

# 4. Run spaCy baseline for NER

In [ ]:
!python src/ner_baseline.py \
  --input data/processed/cleaned_input_mock2.csv \
  --output outputs/ner/ner_results_mock2_baseline.csv \
  --model en_core_web_sm

[ner] Wrote 58 entity mention(s) to: outputs/ner/ner_results_mock2_baseline.csv

In [ ]:
ner_df = pd.read_csv("outputs/ner/ner_results_mock2_baseline.csv")
display(ner_df)

,source_id,source_type,source_type_cleaned,source_url,source_url_cleaned,date,date_cleaned,company_seed,company_seed_cleaned,raw_text,raw_text_cleaned,raw_mention,entity_label,start_char,end_char
0,1,SEC,SEC,https://example.com/sec1,https://example.com/sec1,2023-01,2023-01,Pfizer,Pfizer,Pfizer acquired Seagen in 2023.,Pfizer acquired Seagen in 2023.,Seagen,ORG,16,22
1,3,USPTO,USPTO,https://example.com/uspto1,https://example.com/uspto1,2022-06,2022-06,Regeneron,Regeneron,Regeneron and Sanofi jointly developed an anti...,Regeneron and Sanofi jointly developed an anti...,Sanofi,ORG,14,20
2,4,PUBMED,PUBMED,https://example.com/pubmed1,https://example.com/pubmed1,2021-11,2021-11,CSL Behring,CSL Behring,CSL Behring collaborated with Takeda on plasma...,CSL Behring collaborated with Takeda on plasma...,CSL Behring,ORG,0,11
3,5,SEC,SEC,https://example.com/sec3,https://example.com/sec3,2024-12,2024-12,Bristol Myers Squibb,Bristol Myers Squibb,Bristol Myers Squibb purchased Karuna Therapeu...,Bristol Myers Squibb purchased Karuna Therapeu...,Bristol Myers Squibb,ORG,0,20
4,5,SEC,SEC,https://example.com/sec3,https://example.com/sec3,2024-12,2024-12,Bristol Myers Squibb,Bristol Myers Squibb,Bristol Myers Squibb purchased Karuna Therapeu...,Bristol Myers Squibb purchased Karuna Therapeu...,Karuna Therapeutics,ORG,31,50
5,7,SEC,SEC,https://example.com/sec4,https://example.com/sec4,2023-08,2023-08,AstraZeneca,AstraZeneca,AstraZeneca partnered with Daiichi Sankyo to c...,AstraZeneca partnered with Daiichi Sankyo to c...,AstraZeneca,ORG,0,11
6,7,SEC,SEC,https://example.com/sec4,https://example.com/sec4,2023-08,2023-08,AstraZeneca,AstraZeneca,AstraZeneca partnered with Daiichi Sankyo to c...,AstraZeneca partnered with Daiichi Sankyo to c...,Daiichi Sankyo,ORG,27,41
7,8,PUBMED,PUBMED,https://example.com/pubmed2,https://example.com/pubmed2,2022-03,2022-03,Novartis,Novartis,Novartis worked with Alnylam on RNA interferen...,Novartis worked with Alnylam on RNA interferen...,Novartis,ORG,0,8
8,8,PUBMED,PUBMED,https://example.com/pubmed2,https://example.com/pubmed2,2022-03,2022-03,Novartis,Novartis,Novartis worked with Alnylam on RNA interferen...,Novartis worked with Alnylam on RNA interferen...,RNA,ORG,32,35
9,9,SEC,SEC,https://example.com/sec5,https://example.com/sec5,2024-03,2024-03,10X Genomics,10X Genomics,10X GENOMICS INC acquired a small diagnostics ...,10X GENOMICS INC acquired a small diagnostics ...,GENOMICS INC,ORG,4,16
10,11,SEC,SEC,https://example.com/sec7,https://example.com/sec7,2024-05,2024-05,10X Genomics,10X Genomics,10X GENOMICS SWEDEN AB licensed imaging techno...,10X GENOMICS SWEDEN AB licensed imaging techno...,GENOMICS SWEDEN AB,ORG,4,22
11,11,SEC,SEC,https://example.com/sec7,https://example.com/sec7,2024-05,2024-05,10X Genomics,10X Genomics,10X GENOMICS SWEDEN AB licensed imaging techno...,10X GENOMICS SWEDEN AB licensed imaging techno...,NanoString,ORG,56,66
12,12,PUBMED,PUBMED,https://example.com/pubmed3,https://example.com/pubmed3,2022-09,2022-09,CSL Behring,CSL Behring,CSL Behring GmbH developed a plasma therapy al...,CSL Behring GmbH developed a plasma therapy al...,CSL Behring GmbH,ORG,0,16
13,12,PUBMED,PUBMED,https://example.com/pubmed3,https://example.com/pubmed3,2022-09,2022-09,CSL Behring,CSL Behring,CSL Behring GmbH developed a plasma therapy al...,CSL Behring GmbH developed a plasma therapy al...,CSL Behring Inc.,ORG,54,70
14,13,SEC,SEC,https://example.com/sec8,https://example.com/sec8,2023-02,2023-02,Pfizer,Pfizer,"Pfizer Inc. acquired Seagen, according to the ...","Pfizer Inc. acquired Seagen, according to the ...",Pfizer Inc.,ORG,0,11
15,15,USPTO,USPTO,https://example.com/uspto3,https://example.com/uspto3,2021-07,2021-07,Regeneron,Regeneron,"Regeneron Pharmaceuticals, Inc. and Sanofi co-...","Regeneron Pharmaceuticals, Inc. and Sanofi co-...","Regeneron Pharmaceuticals, Inc.",ORG,0,31
16,17,SEC,SEC,https://example.com/sec10,https://example.com/sec10,2023-10,2023-10,Moderna,Moderna,"Moderna, Inc. entered into a license agree...","Moderna, Inc. entered into a license agreement...","Moderna, Inc.",ORG,0,13
17,17,SEC,SEC,https://example.com/sec10,https://example.com/sec10,2023-10,2023-10,Moderna,Moderna,"Moderna, Inc. entered into a license agree...","Moderna, Inc. entered into a license agreement...",Vertex Pharmaceuticals,ORG,52,74
18,18,SEC,SEC,https://example.com/sec11,https://example.com/sec11,2024-01,2024-01,Gilead Sciences,Gilead Sciences,"Gilead Sciences, Inc. acquired CymaBay Thera...","Gilead Sciences, Inc. acquired CymaBay Therape...","Gilead Sciences, Inc.",ORG,0,21
19,18,SEC,SEC,https://example.com/sec11,https://example.com/sec11,2024-01,2024-01,Gilead Sciences,Gilead Sciences,"Gilead Sciences, Inc. acquired CymaBay Thera...","Gilead Sciences, Inc. acquired CymaBay Therape...",CymaBay Therapeutics,ORG,31,51
20,19,USPTO,USPTO,https://example.com/uspto4,https://example.com/uspto4,2021-05,2021-05,argenx,argenx,argenx SE co-filed a patent with Johnson & Joh...,argenx SE co-filed a patent with Johnson & Joh...,Johnson & Johnson,ORG,33,50
21,20,PUBMED,PUBMED,https://example.com/pubmed5,https://example.com/pubmed5,2020-08,2020-08,bluebird bio,bluebird bio,bluebird bio partnered with Bristol-Myers Squi...,bluebird bio partnered with Bristol-Myers Squi...,Bristol-Myers Squibb,ORG,28,48
22,21,SEC,SEC,https://example.com/sec12,https://example.com/sec12,2022-04,2022-04,Sarepta Therapeutics,Sarepta Therapeutics,Sarepta Therapeutics merged with Example Rare ...,Sarepta Therapeutics merged with Example Rare ...,Sarepta Therapeutics,ORG,0,20
23,21,SEC,SEC,https://example.com/sec12,https://example.com/sec12,2022-04,2022-04,Sarepta Therapeutics,Sarepta Therapeutics,Sarepta Therapeutics merged with Example Rare ...,Sarepta Therapeutics merged with Example Rare ...,Example Rare Disease Co.,ORG,33,57
24,22,PUBMED,PUBMED,https://example.com/pubmed6,https://example.com/pubmed6,2022-10,2022-10,CRISPR Therapeutics,CRISPR Therapeutics,CRISPR Therapeutics collaborated with Vertex P...,CRISPR Therapeutics collaborated with Vertex P...,CRISPR Therapeutics,ORG,0,19
25,22,PUBMED,PUBMED,https://example.com/pubmed6,https://example.com/pubmed6,2022-10,2022-10,CRISPR Therapeutics,CRISPR Therapeutics,CRISPR Therapeutics collaborated with Vertex P...,CRISPR Therapeutics collaborated with Vertex P...,Vertex Pharmaceuticals,ORG,38,60
26,33,SEC,SEC,https://example.com/sec13,https://example.com/sec13,2023-01,2023-01,Pfizer,Pfizer,Pfizer acquired Seagen in 2023. The deal expan...,Pfizer acquired Seagen in 2023. The deal expan...,Seagen,ORG,16,22
27,34,SEC,SEC,https://example.com/sec14,https://example.com/sec14,2024-02,2024-02,Merck,Merck,"Merck licensed technology from Moderna. Later,...","Merck licensed technology from Moderna. Later,...",Merck,ORG,0,5
28,34,SEC,SEC,https://example.com/sec14,https://example.com/sec14,2024-02,2024-02,Merck,Merck,"Merck licensed technology from Moderna. Later,...","Merck licensed technology from Moderna. Later,...",Merck,ORG,47,52
29,37,SEC,SEC,https://example.com/sec15,https://example.com/sec15,2023-09,2023-09,CSL Behring,CSL Behring,CSL Behring and CSL Behring GmbH were both ref...,CSL Behring and CSL Behring GmbH were both ref...,CSL Behring,ORG,0,11
30,37,SEC,SEC,https://example.com/sec15,https://example.com/sec15,2023-09,2023-09,CSL Behring,CSL Behring,CSL Behring and CSL Behring GmbH were both ref...,CSL Behring and CSL Behring GmbH were both ref...,CSL Behring GmbH,ORG,16,32
31,38,SEC,SEC,https://example.com/sec16,https://example.com/sec16,2024-07,2024-07,10X Genomics,10X Genomics,10X Genomics Sweden AB and 10X Genomics BV wer...,10X Genomics Sweden AB and 10X Genomics BV wer...,Genomics Sweden AB,ORG,4,22
32,39,PUBMED,PUBMED,https://example.com/pubmed8,https://example.com/pubmed8,2022-01,2022-01,Johnson & Johnson,Johnson & Johnson,J&J worked with Johnson and Johnson Innovative...,J&J worked with Johnson and Johnson Innovative...,J&J,ORG,0,3
33,39,PUBMED,PUBMED,https://example.com/pubmed8,https://example.com/pubmed8,2022-01,2022-01,Johnson & Johnson,Johnson & Johnson,J&J worked with Johnson and Johnson Innovative...,J&J worked with Johnson and Johnson Innovative...,Johnson Innovative Medicine,ORG,28,55
34,40,USPTO,USPTO,https://example.com/uspto6,https://example.com/uspto6,2021-03,2021-03,Regeneron,Regeneron,"Regeneron and Regeneron Pharmaceuticals, Inc. ...","Regeneron and Regeneron Pharmaceuticals, Inc. ...",Regeneron Pharmaceuticals,ORG,14,39
35,41,SEC,SEC,https://example.com/sec17,https://example.com/sec17,2023-10,2023-10,Eli Lilly,Eli Lilly,Eli Lilly acquired POINT Biopharma to strength...,Eli Lilly acquired POINT Biopharma to strength...,Eli Lilly,ORG,0,9
36,42,SEC,SEC,https://example.com/sec18,https://example.com/sec18,2024-01,2024-01,Roche,Roche,Roche entered into a collaboration with Recurs...,Roche entered into a collaboration with Recurs...,Roche,ORG,0,5
37,42,SEC,SEC,https://example.com/sec18,https://example.com/sec18,2024-01,2024-01,Roche,Roche,Roche entered into a collaboration with Recurs...,Roche entered into a collaboration with Recurs...,Recursion Pharmaceuticals,ORG,40,65
38,43,PUBMED,PUBMED,https://example.com/pubmed9,https://example.com/pubmed9,2021-04,2021-04,Takeda,Takeda,Takeda worked with Arrowhead Pharmaceuticals o...,Takeda worked with Arrowhead Pharmaceuticals o...,Arrowhead Pharmaceuticals,ORG,19,44
39,44,USPTO,USPTO,https://example.com/uspto7,https://example.com/uspto7,2024-02,2024-02,Amgen,Amgen,Amgen co-filed a patent with Generate Biomedic...,Amgen co-filed a patent with Generate Biomedic...,Amgen,ORG,0,5
40,45,SEC,SEC,https://example.com/sec19,https://example.com/sec19,2023-11,2023-11,Biogen,Biogen,Biogen licensed a neurodegeneration program fr...,Biogen licensed a neurodegeneration program fr...,Biogen,ORG,0,6
41,45,SEC,SEC,https://example.com/sec19,https://example.com/sec19,2023-11,2023-11,Biogen,Biogen,Biogen licensed a neurodegeneration program fr...,Biogen licensed a neurodegeneration program fr...,Stoke Therapeutics,ORG,49,67
42,46,PUBMED,PUBMED,https://example.com/pubmed10,https://example.com/pubmed10,2022-05,2022-05,GSK,GSK,GSK partnered with CureVac on next-generation ...,GSK partnered with CureVac on next-generation ...,GSK,ORG,0,3
43,46,PUBMED,PUBMED,https://example.com/pubmed10,https://example.com/pubmed10,2022-05,2022-05,GSK,GSK,GSK partnered with CureVac on next-generation ...,GSK partnered with CureVac on next-generation ...,CureVac,ORG,19,26
44,47,SEC,SEC,https://example.com/sec20,https://example.com/sec20,2024-06,2024-06,Johnson & Johnson,Johnson & Johnson,Johnson & Johnson acquired Shockwave Medical.,Johnson & Johnson acquired Shockwave Medical.,Johnson & Johnson,ORG,0,17
45,47,SEC,SEC,https://example.com/sec20,https://example.com/sec20,2024-06,2024-06,Johnson & Johnson,Johnson & Johnson,Johnson & Johnson acquired Shockwave Medical.,Johnson & Johnson acquired Shockwave Medical.,Shockwave Medical,ORG,27,44
46,48,USPTO,USPTO,https://example.com/uspto8,https://example.com/uspto8,2023-12,2023-12,Novo Nordisk,Novo Nordisk,Novo Nordisk filed patent with Valo Health on ...,Novo Nordisk filed patent with Valo Health on ...,Valo Health,ORG,31,42
47,49,SEC,SEC,NaN,NaN,2023-13,2023-13,Acme Bio,Acme Bio,Acme Bio collaborated with Beta Pharma.,Acme Bio collaborated with Beta Pharma.,Acme Bio,ORG,0,8
48,51,SEC,SEC,https://example.com/sec21,https://example.com/sec21,2023-09,2023-09,Pfizer,Pfizer,BioNTech entered into a collaboration with Gen...,BioNTech entered into a collaboration with Gen...,Genentech,ORG,43,52
49,54,PUBMED,PUBMED,https://example.com/pubmed12,https://example.com/pubmed12,2021-02,2021-02,Seagen,Seagen,Seagen/Genmab collaboration was discussed in t...,Seagen/Genmab collaboration was discussed in t...,Seagen/Genmab,ORG,0,13
50,55,USPTO,USPTO,https://example.com/uspto9,https://example.com/uspto9,2024-03,2024-03,Merck,Merck,"Merck & Co., Inc.; Moderna, Inc. ; and BioNTec...","Merck & Co., Inc.; Moderna, Inc. ; and BioNTec...",Merck & Co.,ORG,0,11
51,56,SEC,SEC,https://example.com/sec23,https://example.com/sec23,2024-04,2024-04,Pfizer,Pfizer,Pfizer licensed technology from Beam ...,Pfizer licensed technology from Beam Therapeutics,Beam Therapeutics,ORG,32,49
52,57,PUBMED,PUBMED,https://example.com/pubmed13,https://example.com/pubmed13,2022-06,2022-06,Pfizer,Pfizer,FDA collaborated with Pfizer on regulatory sci...,FDA collaborated with Pfizer on regulatory sci...,FDA,ORG,0,3
53,58,SEC,SEC,https://example.com/sec24,https://example.com/sec24,2020-09,2020-09,Spark Therapeutics,Spark Therapeutics,University of Pennsylvania licensed technology...,University of Pennsylvania licensed technology...,University of Pennsylvania,ORG,0,26
54,58,SEC,SEC,https://example.com/sec24,https://example.com/sec24,2020-09,2020-09,Spark Therapeutics,Spark Therapeutics,University of Pennsylvania licensed technology...,University of Pennsylvania licensed technology...,Spark Therapeutics,ORG,50,68
55,59,SEC,SEC,not_a_url,not_a_url,2024-05,2024-05,Alnylam,Alnylam,Alnylam acquired Example RNA Startup.,Alnylam acquired Example RNA Startup.,Alnylam,ORG,0,7
56,59,SEC,SEC,not_a_url,not_a_url,2024-05,2024-05,Alnylam,Alnylam,Alnylam acquired Example RNA Startup.,Alnylam acquired Example RNA Startup.,Example RNA Startup,ORG,17,36
57,60,PUBMED,PUBMED,https://example.com/pubmed14,https://example.com/pubmed14,NaN,NaN,Example Biotech,Example Biotech,Example Biotech worked with Example Diagnostics.,Example Biotech worked with Example Diagnostics.,Example Diagnostics,ORG,28,47

# 5. Run alias resolution

In [ ]:
!python src/resolve_alias.py \
  --input outputs/ner/ner_results_mock2_baseline.csv \
  --resolved-output outputs/entity_resolution/resolved_entities_mock2_baseline.csv \
  --review-output outputs/entity_resolution/review_queue_mock2_baseline.csv

[resolve_alias] Wrote 58 resolved row(s) to: outputs/entity_resolution/resolved_entities_mock2_baseline.csv
[resolve_alias] Wrote 3 review pair(s) to: outputs/entity_resolution/review_queue_mock2_baseline.csv

In [ ]:
import os

for path in [
    "outputs/entity_resolution/resolved_entities_mock2_baseline.csv",
    "outputs/entity_resolution/review_queue_mock2_baseline.csv",
]:
    print(path)
    print("exists:", os.path.exists(path))
    if os.path.exists(path):
        print("size:", os.path.getsize(path), "bytes")
    print("-" * 40)

outputs/entity_resolution/resolved_entities_mock2_baseline.csv
exists: True
size: 13889 bytes
----------------------------------------
outputs/entity_resolution/review_queue_mock2_baseline.csv
exists: True
size: 421 bytes
----------------------------------------

# 6. Candidate relations

In [ ]:
import pandas as pd

resolved_df = pd.read_csv("outputs/entity_resolution/resolved_entities_mock2_baseline.csv")
display(resolved_df)

,source_id,source_type,source_url,date,company_seed,raw_text,raw_mention,entity_label,start_char,end_char,normalized_name,base_name,legal_suffixes,canonical_group_id,canonical_name,merge_confidence,merge_decision,evidence_note
0,1,SEC,https://example.com/sec1,2023-01,Pfizer,Pfizer acquired Seagen in 2023.,Seagen,ORG,16,22,SEAGEN,SEAGEN,NaN,42,Seagen,1.00,singleton,singleton_no_merge_needed
1,3,USPTO,https://example.com/uspto1,2022-06,Regeneron,Regeneron and Sanofi jointly developed an anti...,Sanofi,ORG,14,20,SANOFI,SANOFI,NaN,21,Sanofi,1.00,singleton,singleton_no_merge_needed
2,4,PUBMED,https://example.com/pubmed1,2021-11,CSL Behring,CSL Behring collaborated with Takeda on plasma...,CSL Behring,ORG,0,11,CSL BEHRING,CSL BEHRING,NaN,11,CSL Behring,0.88,auto_merge,auto_merge_component
3,5,SEC,https://example.com/sec3,2024-12,Bristol Myers Squibb,Bristol Myers Squibb purchased Karuna Therapeu...,Bristol Myers Squibb,ORG,0,20,BRISTOL MYERS SQUIBB,BRISTOL MYERS SQUIBB,NaN,9,Bristol-Myers Squibb,1.00,singleton,singleton_no_merge_needed
4,5,SEC,https://example.com/sec3,2024-12,Bristol Myers Squibb,Bristol Myers Squibb purchased Karuna Therapeu...,Karuna Therapeutics,ORG,31,50,KARUNA THERAPEUTICS,KARUNA THERAPEUTICS,NaN,40,Karuna Therapeutics,1.00,singleton,singleton_no_merge_needed
5,7,SEC,https://example.com/sec4,2023-08,AstraZeneca,AstraZeneca partnered with Daiichi Sankyo to c...,AstraZeneca,ORG,0,11,ASTRAZENECA,ASTRAZENECA,NaN,37,AstraZeneca,1.00,singleton,singleton_no_merge_needed
6,7,SEC,https://example.com/sec4,2023-08,AstraZeneca,AstraZeneca partnered with Daiichi Sankyo to c...,Daiichi Sankyo,ORG,27,41,DAIICHI SANKYO,DAIICHI SANKYO,NaN,31,Daiichi Sankyo,1.00,singleton,singleton_no_merge_needed
7,8,PUBMED,https://example.com/pubmed2,2022-03,Novartis,Novartis worked with Alnylam on RNA interferen...,Novartis,ORG,0,8,NOVARTIS,NOVARTIS,NaN,39,Novartis,1.00,singleton,singleton_no_merge_needed
8,8,PUBMED,https://example.com/pubmed2,2022-03,Novartis,Novartis worked with Alnylam on RNA interferen...,RNA,ORG,32,35,RNA,RNA,NaN,13,RNA,1.00,singleton,singleton_no_merge_needed
9,9,SEC,https://example.com/sec5,2024-03,10X Genomics,10X GENOMICS INC acquired a small diagnostics ...,GENOMICS INC,ORG,4,16,GENOMICS INC,GENOMICS,INC,44,GENOMICS INC,1.00,singleton,singleton_no_merge_needed
10,11,SEC,https://example.com/sec7,2024-05,10X Genomics,10X GENOMICS SWEDEN AB licensed imaging techno...,GENOMICS SWEDEN AB,ORG,4,22,GENOMICS SWEDEN AB,GENOMICS SWEDEN,AB,24,Genomics Sweden AB,1.00,singleton,singleton_no_merge_needed
11,11,SEC,https://example.com/sec7,2024-05,10X Genomics,10X GENOMICS SWEDEN AB licensed imaging techno...,NanoString,ORG,56,66,NANOSTRING,NANOSTRING,NaN,26,NanoString,1.00,singleton,singleton_no_merge_needed
12,12,PUBMED,https://example.com/pubmed3,2022-09,CSL Behring,CSL Behring GmbH developed a plasma therapy al...,CSL Behring GmbH,ORG,0,16,CSL BEHRING GMBH,CSL BEHRING,GMBH,16,CSL Behring GmbH,0.55,review_needed,same_base_name_but_suffix_differs
13,12,PUBMED,https://example.com/pubmed3,2022-09,CSL Behring,CSL Behring GmbH developed a plasma therapy al...,CSL Behring Inc.,ORG,54,70,CSL BEHRING INC,CSL BEHRING,INC,11,CSL Behring,0.88,auto_merge,auto_merge_component
14,13,SEC,https://example.com/sec8,2023-02,Pfizer,"Pfizer Inc. acquired Seagen, according to the ...",Pfizer Inc.,ORG,0,11,PFIZER INC,PFIZER,INC,25,Pfizer Inc.,1.00,singleton,singleton_no_merge_needed
15,15,USPTO,https://example.com/uspto3,2021-07,Regeneron,"Regeneron Pharmaceuticals, Inc. and Sanofi co-...","Regeneron Pharmaceuticals, Inc.",ORG,0,31,REGENERON PHARMACEUTICALS INC,REGENERON PHARMACEUTICALS,INC,14,"Regeneron Pharmaceuticals, Inc.",0.88,auto_merge,auto_merge_component
16,17,SEC,https://example.com/sec10,2023-10,Moderna,"Moderna, Inc. entered into a license agree...","Moderna, Inc.",ORG,0,13,MODERNA INC,MODERNA,INC,1,"Moderna, Inc.",1.00,singleton,singleton_no_merge_needed
17,17,SEC,https://example.com/sec10,2023-10,Moderna,"Moderna, Inc. entered into a license agree...",Vertex Pharmaceuticals,ORG,52,74,VERTEX PHARMACEUTICALS,VERTEX PHARMACEUTICALS,NaN,10,Vertex Pharmaceuticals,1.00,singleton,singleton_no_merge_needed
18,18,SEC,https://example.com/sec11,2024-01,Gilead Sciences,"Gilead Sciences, Inc. acquired CymaBay Thera...","Gilead Sciences, Inc.",ORG,0,21,GILEAD SCIENCES INC,GILEAD SCIENCES,INC,43,"Gilead Sciences, Inc.",1.00,singleton,singleton_no_merge_needed
19,18,SEC,https://example.com/sec11,2024-01,Gilead Sciences,"Gilead Sciences, Inc. acquired CymaBay Thera...",CymaBay Therapeutics,ORG,31,51,CYMABAY THERAPEUTICS,CYMABAY THERAPEUTICS,NaN,3,CymaBay Therapeutics,1.00,singleton,singleton_no_merge_needed
20,19,USPTO,https://example.com/uspto4,2021-05,argenx,argenx SE co-filed a patent with Johnson & Joh...,Johnson & Johnson,ORG,33,50,JOHNSON AND JOHNSON,JOHNSON AND JOHNSON,NaN,7,Johnson & Johnson,1.00,singleton,singleton_no_merge_needed
21,20,PUBMED,https://example.com/pubmed5,2020-08,bluebird bio,bluebird bio partnered with Bristol-Myers Squi...,Bristol-Myers Squibb,ORG,28,48,BRISTOL MYERS SQUIBB,BRISTOL MYERS SQUIBB,NaN,9,Bristol-Myers Squibb,1.00,singleton,singleton_no_merge_needed
22,21,SEC,https://example.com/sec12,2022-04,Sarepta Therapeutics,Sarepta Therapeutics merged with Example Rare ...,Sarepta Therapeutics,ORG,0,20,SAREPTA THERAPEUTICS,SAREPTA THERAPEUTICS,NaN,27,Sarepta Therapeutics,1.00,singleton,singleton_no_merge_needed
23,21,SEC,https://example.com/sec12,2022-04,Sarepta Therapeutics,Sarepta Therapeutics merged with Example Rare ...,Example Rare Disease Co.,ORG,33,57,EXAMPLE RARE DISEASE CO,EXAMPLE RARE DISEASE,CO,6,Example Rare Disease Co.,1.00,singleton,singleton_no_merge_needed
24,22,PUBMED,https://example.com/pubmed6,2022-10,CRISPR Therapeutics,CRISPR Therapeutics collaborated with Vertex P...,CRISPR Therapeutics,ORG,0,19,CRISPR THERAPEUTICS,CRISPR THERAPEUTICS,NaN,48,CRISPR Therapeutics,0.50,review_needed,high_string_similarity
25,22,PUBMED,https://example.com/pubmed6,2022-10,CRISPR Therapeutics,CRISPR Therapeutics collaborated with Vertex P...,Vertex Pharmaceuticals,ORG,38,60,VERTEX PHARMACEUTICALS,VERTEX PHARMACEUTICALS,NaN,10,Vertex Pharmaceuticals,1.00,singleton,singleton_no_merge_needed
26,33,SEC,https://example.com/sec13,2023-01,Pfizer,Pfizer acquired Seagen in 2023. The deal expan...,Seagen,ORG,16,22,SEAGEN,SEAGEN,NaN,42,Seagen,1.00,singleton,singleton_no_merge_needed
27,34,SEC,https://example.com/sec14,2024-02,Merck,"Merck licensed technology from Moderna. Later,...",Merck,ORG,0,5,MERCK,MERCK,NaN,23,Merck,1.00,singleton,singleton_no_merge_needed
28,34,SEC,https://example.com/sec14,2024-02,Merck,"Merck licensed technology from Moderna. Later,...",Merck,ORG,47,52,MERCK,MERCK,NaN,23,Merck,1.00,singleton,singleton_no_merge_needed
29,37,SEC,https://example.com/sec15,2023-09,CSL Behring,CSL Behring and CSL Behring GmbH were both ref...,CSL Behring,ORG,0,11,CSL BEHRING,CSL BEHRING,NaN,11,CSL Behring,0.88,auto_merge,auto_merge_component
30,37,SEC,https://example.com/sec15,2023-09,CSL Behring,CSL Behring and CSL Behring GmbH were both ref...,CSL Behring GmbH,ORG,16,32,CSL BEHRING GMBH,CSL BEHRING,GMBH,16,CSL Behring GmbH,0.55,review_needed,same_base_name_but_suffix_differs
31,38,SEC,https://example.com/sec16,2024-07,10X Genomics,10X Genomics Sweden AB and 10X Genomics BV wer...,Genomics Sweden AB,ORG,4,22,GENOMICS SWEDEN AB,GENOMICS SWEDEN,AB,24,Genomics Sweden AB,1.00,singleton,singleton_no_merge_needed
32,39,PUBMED,https://example.com/pubmed8,2022-01,Johnson & Johnson,J&J worked with Johnson and Johnson Innovative...,J&J,ORG,0,3,J AND J,J AND J,NaN,4,J&J,1.00,singleton,singleton_no_merge_needed
33,39,PUBMED,https://example.com/pubmed8,2022-01,Johnson & Johnson,J&J worked with Johnson and Johnson Innovative...,Johnson Innovative Medicine,ORG,28,55,JOHNSON INNOVATIVE MEDICINE,JOHNSON INNOVATIVE MEDICINE,NaN,18,Johnson Innovative Medicine,1.00,singleton,singleton_no_merge_needed
34,40,USPTO,https://example.com/uspto6,2021-03,Regeneron,"Regeneron and Regeneron Pharmaceuticals, Inc. ...",Regeneron Pharmaceuticals,ORG,14,39,REGENERON PHARMACEUTICALS,REGENERON PHARMACEUTICALS,NaN,14,"Regeneron Pharmaceuticals, Inc.",0.88,auto_merge,auto_merge_component
35,41,SEC,https://example.com/sec17,2023-10,Eli Lilly,Eli Lilly acquired POINT Biopharma to strength...,Eli Lilly,ORG,0,9,ELI LILLY,ELI LILLY,NaN,17,Eli Lilly,1.00,singleton,singleton_no_merge_needed
36,42,SEC,https://example.com/sec18,2024-01,Roche,Roche entered into a collaboration with Recurs...,Roche,ORG,0,5,ROCHE,ROCHE,NaN,47,Roche,1.00,singleton,singleton_no_merge_needed
37,42,SEC,https://example.com/sec18,2024-01,Roche,Roche entered into a collaboration with Recurs...,Recursion Pharmaceuticals,ORG,40,65,RECURSION PHARMACEUTICALS,RECURSION PHARMACEUTICALS,NaN,8,Recursion Pharmaceuticals,1.00,singleton,singleton_no_merge_needed
38,43,PUBMED,https://example.com/pubmed9,2021-04,Takeda,Takeda worked with Arrowhead Pharmaceuticals o...,Arrowhead Pharmaceuticals,ORG,19,44,ARROWHEAD PHARMACEUTICALS,ARROWHEAD PHARMACEUTICALS,NaN,41,Arrowhead Pharmaceuticals,1.00,singleton,singleton_no_merge_needed
39,44,USPTO,https://example.com/uspto7,2024-02,Amgen,Amgen co-filed a patent with Generate Biomedic...,Amgen,ORG,0,5,AMGEN,AMGEN,NaN,38,Amgen,1.00,singleton,singleton_no_merge_needed
40,45,SEC,https://example.com/sec19,2023-11,Biogen,Biogen licensed a neurodegeneration program fr...,Biogen,ORG,0,6,BIOGEN,BIOGEN,NaN,45,Biogen,1.00,singleton,singleton_no_merge_needed
41,45,SEC,https://example.com/sec19,2023-11,Biogen,Biogen licensed a neurodegeneration program fr...,Stoke Therapeutics,ORG,49,67,STOKE THERAPEUTICS,STOKE THERAPEUTICS,NaN,12,Stoke Therapeutics,1.00,singleton,singleton_no_merge_needed
42,46,PUBMED,https://example.com/pubmed10,2022-05,GSK,GSK partnered with CureVac on next-generation ...,GSK,ORG,0,3,GSK,GSK,NaN,35,GSK,1.00,singleton,singleton_no_merge_needed
43,46,PUBMED,https://example.com/pubmed10,2022-05,GSK,GSK partnered with CureVac on next-generation ...,CureVac,ORG,19,26,CUREVAC,CUREVAC,NaN,20,CureVac,1.00,singleton,singleton_no_merge_needed
44,47,SEC,https://example.com/sec20,2024-06,Johnson & Johnson,Johnson & Johnson acquired Shockwave Medical.,Johnson & Johnson,ORG,0,17,JOHNSON AND JOHNSON,JOHNSON AND JOHNSON,NaN,7,Johnson & Johnson,1.00,singleton,singleton_no_merge_needed
45,47,SEC,https://example.com/sec20,2024-06,Johnson & Johnson,Johnson & Johnson acquired Shockwave Medical.,Shockwave Medical,ORG,27,44,SHOCKWAVE MEDICAL,SHOCKWAVE MEDICAL,NaN,36,Shockwave Medical,1.00,singleton,singleton_no_merge_needed
46,48,USPTO,https://example.com/uspto8,2023-12,Novo Nordisk,Novo Nordisk filed patent with Valo Health on ...,Valo Health,ORG,31,42,VALO HEALTH,VALO HEALTH,NaN,29,Valo Health,1.00,singleton,singleton_no_merge_needed
47,49,SEC,NaN,2023-13,Acme Bio,Acme Bio collaborated with Beta Pharma.,Acme Bio,ORG,0,8,ACME BIO,ACME BIO,NaN,28,Acme Bio,1.00,singleton,singleton_no_merge_needed
48,51,SEC,https://example.com/sec21,2023-09,Pfizer,BioNTech entered into a collaboration with Gen...,Genentech,ORG,43,52,GENENTECH,GENENTECH,NaN,19,Genentech,1.00,singleton,singleton_no_merge_needed
49,54,PUBMED,https://example.com/pubmed12,2021-02,Seagen,Seagen/Genmab collaboration was discussed in t...,Seagen/Genmab,ORG,0,13,SEAGEN GENMAB,SEAGEN GENMAB,NaN,46,Seagen/Genmab,1.00,singleton,singleton_no_merge_needed
50,55,USPTO,https://example.com/uspto9,2024-03,Merck,"Merck & Co., Inc.; Moderna, Inc. ; and BioNTec...",Merck & Co.,ORG,0,11,MERCK AND CO,MERCK AND,CO,5,Merck & Co.,1.00,singleton,singleton_no_merge_needed
51,56,SEC,https://example.com/sec23,2024-04,Pfizer,Pfizer licensed technology from Beam ...,Beam Therapeutics,ORG,32,49,BEAM THERAPEUTICS,BEAM THERAPEUTICS,NaN,15,Beam Therapeutics,1.00,singleton,singleton_no_merge_needed
52,57,PUBMED,https://example.com/pubmed13,2022-06,Pfizer,FDA collaborated with Pfizer on regulatory sci...,FDA,ORG,0,3,FDA,FDA,NaN,22,FDA,1.00,singleton,singleton_no_merge_needed
53,58,SEC,https://example.com/sec24,2020-09,Spark Therapeutics,University of Pennsylvania licensed technology...,University of Pennsylvania,ORG,0,26,UNIVERSITY OF PENNSYLVANIA,UNIVERSITY OF PENNSYLVANIA,NaN,2,University of Pennsylvania,1.00,singleton,singleton_no_merge_needed
54,58,SEC,https://example.com/sec24,2020-09,Spark Therapeutics,University of Pennsylvania licensed technology...,Spark Therapeutics,ORG,50,68,SPARK THERAPEUTICS,SPARK THERAPEUTICS,NaN,30,Spark Therapeutics,0.50,review_needed,high_string_similarity
55,59,SEC,not_a_url,2024-05,Alnylam,Alnylam acquired Example RNA Startup.,Alnylam,ORG,0,7,ALNYLAM,ALNYLAM,NaN,32,Alnylam,1.00,singleton,singleton_no_merge_needed
56,59,SEC,not_a_url,2024-05,Alnylam,Alnylam acquired Example RNA Startup.,Example RNA Startup,ORG,17,36,EXAMPLE RNA STARTUP,EXAMPLE RNA STARTUP,NaN,33,Example RNA Startup,1.00,singleton,singleton_no_merge_needed
57,60,PUBMED,https://example.com/pubmed14,NaN,Example Biotech,Example Biotech worked with Example Diagnostics.,Example Diagnostics,ORG,28,47,EXAMPLE DIAGNOSTICS,EXAMPLE DIAGNOSTICS,NaN,34,Example Diagnostics,1.00,singleton,singleton_no_merge_needed

In [ ]:
!mkdir -p outputs/relations

!python src/extract_candidate_relations.py \
  --input outputs/entity_resolution/resolved_entities_mock2_baseline.csv \
  --output outputs/relations/candidate_relations_mock2_baseline.csv

[extract_candidate_relations] Wrote 13 candidate row(s) to: outputs/relations/candidate_relations_mock2_baseline.csv